
--- 
title: Key tropical crops at risk from pollinator loss due to climate change and land use
author: 
- Joseph Millard^1,^^2^\*, Charlotte L. Outhwaite^2^, Silvia Ceaușu^2^, Luísa G. Carvalheiro^3,^^4^, 
-  Felipe Deodato da Silva e Silva^5^, Lynn V. Dicks^6^, Jeff Ollerton^7^, Tim Newbold^2^\newline
output:
  bookdown::pdf_document2:
    latex_engine: pdflatex
    toc: false
    number_sections: false
markdown_extensions:
- codehilite:
    linenums: true
always_allow_html: true
csl: nature.csl
bibliography: lu_cc_pollin_refs.bib
header-includes:
  \usepackage{float}
  \floatplacement{figure}{H}
  \usepackage[left]{lineno}
   \renewcommand{\linenumberfont}{\normalfont\bfseries\small\color{gray}}
  \linenumbers
---
^1^ Department of Life Sciences, Natural History Museum, Cromwell Road, London SW7 5BD, UK

^2^ Centre for Biodiversity and Environment Research, Department of Genetics, Evolution and Environment, University College London, London, WC1E 6BT, UK

^3^ Department of Ecology, Federal University of Goiás, Goiânia-GO, 74690-900, Brazil.

^4^ Center for Ecology, Evolution and Environmental Change (CE3C), University of Lisbon, Lisbon, Portugal.

^5^ Federal Institute of Education, Science and Technology of Mato Grosso (IFMT)—Campus Barra do Garças, Barra do Garças-MT, 78600-000, Brazil.

^6^ Department of Zoology, University of Cambridge, Downing Street, Cambridge CB2 3EJ, UK

^7^ Faculty of Arts, Science & Technology, University of Northampton. University Drive, Northampton, NN1 5PH UK

*Corresponding author. Email: joseph.millard@nhm.ac.uk

# One sentence summary
Pollinator losses from agriculture and climate change risk production of key crops in the tropics, especially cocoa.

# Short title
Pollinator losses and crop pollination risk.

# Abstract

Insect pollinator biodiversity has been shown to be changing rapidly, with potential consequences for the provision of crop pollination. However, the role of land-use-climate interactions in pollinator biodiversity changes, and consequent economic effects via changes in crop pollination, remains poorly understood. Here, we present a global assessment of the interactive effects of climate change and land use on pollinator abundance and richness, and predictions of the risk to crop pollination from the inferred changes. Using a dataset containing 2673 sites and 3080 insect pollinator species, we show that the interactive combination of agriculture and climate change is associated with large reductions in the abundance and richness of insect pollinators. As a result, it is expected that the tropics will experience the greatest risk to crop production from pollinator losses. Localised risk is highest, and predicted to increase most rapidly, in regions of sub-Saharan Africa, northern South America, and south-east Asia. Via pollinator loss alone, climate change and agricultural land use could be a risk to human health and well-being.

# Introduction

Recent studies have highlighted rapid ongoing changes in terrestrial insect biodiversity [@vanKlink2020; @Dornelas2019; @Lister2018], including among pollinating species [@Biesmeijer2006; @Potts2010; @Oliver2015; @Powney2019; @Soroye2020]. Some of these studies have reported net declines [@vanKlink2020; @Lister2018], while others have shown mixtures of gains and losses [@Dornelas2019]. Pollinator biodiversity changes have potential consequences for the provision of pollination to wild plants and crops. Importantly, evidence for insect biodiversity trends has been biased toward Western Europe and North America [@Basset2019; @Wagner2020], with little coverage of tropical and subtropical regions [@khan2022; @lewinsohn2022]. Although a few studies have shown steep declines of insects in the tropics [@Lister2018], evidence about insect biodiversity trends there often remains anecdotal [@Janzen2019], with global syntheses [@Dornelas2019; @vanKlink2020] having strong geographic biases towards non-tropical regions.

Among the drivers of insect and pollinator biodiversity changes, human-driven land-use changes and climate change are prominent [@Potts2010; @Wagner2020; @Warren2001; @DePalma2016; @Oliver2016; @Millard2021]. Climate change, in particular, is emerging as an increasingly important driver [@Warren2001; @Hickling2006; @Martay2017; @Soroye2020; @Lenoir2020; @Halsch2021], although among taxa responses are likely mixed to some extent [@frund2013]. Synergistic interactive effects of land-use and climate change are often associated with further reductions in insect biodiversity compared to if the pressures acted in isolation [@Suggitt2018; @Platts2019; @Oliver2017; @Peters2019; @outhwaite2022]. A key mechanism underpinning interactive land use and climate effects is the altered microclimatic conditions in areas where vegetation has been modified for human land use [@Suggitt2018]. Tropical insects are expected to be more susceptible to climate change, including interactive effects with land use, given their narrower physiological tolerance compared to non-tropical species [@Deutsch2008]. Indeed, recent studies show greater effects in tropical than non-tropical insect biodiversity [@outhwaite2022].

Changes in the biodiversity and composition of pollinator communities are expected to have large effects on the provision of pollination services. Pollen limitation from animal pollinator losses has already been shown to reduce the reproductive success of wild plants [@Biesmeijer2006; @Rodger2021], and the productivity of certain crops [@Klein2003; @Ricketts2004; @Holzschuh2011; @Woodcock2019; @garibaldi2016], although there is no clear evidence that pollen limitation is yet causing wholesale reductions in yields of crops that rely on animal pollination [@Aizen2008]. Evidence that insect biodiversity responds to human pressures more strongly in the tropics than elsewhere [@Millard2021; @outhwaite2022] is noteworthy, given that the majority of animal-pollination-dependent crops are grown in the tropics [@Klein2007]. However, it is not only tropical countries that will experience the effects of pollinator losses and subsequent pollen limitation, with high income countries benefiting from imports of animal-pollination-dependent foods from tropical areas [@silva2021]. Abundance, species diversity, and functional diversity of pollinators have all been implicated as determinants of the delivery of pollination service [@Albrecht2012; @Brittain2013; @Genung2017; @Winfree2018; @Woodcock2019; @Dainese2019]. Previous attempts to model the provision of crop pollination service are often based on predictions of pollinator abundance, which bears a direct relation to pollination of plants, and has been shown to give a reasonable approximation of pollen deposition in at least some study systems [@Lonsdorf2009]. A key uncertainty however relates to the shape of the functional relationship between pollinator abundance and crop production [@Lonsdorf2009].

Here, we present a global assessment of the interactive effects of climate change and land use on pollinator abundance, and predictions of how the inferred abundance changes might translate into risk to crop pollination worldwide based on a range of possible abundance-pollination relationships. Because species richness has also shown to be important for provision of crop pollination, we also tested the robustness of our models and projections to using Chao-estimated species richness in place of total abundance [@chao2005]. Our underlying analyses are based on a space-for-time framework using the PREDICTS (Projecting Responses of Ecological Diversity In Changing Terrestrial Systems) database of biodiversity recorded in different land uses [@Hudson2017], together with a list of species identified in the literature as likely pollinators [@Millard2021]. We use mixed-effects models to fit total pollinator community abundance as a function of land use (primary vegetation versus cropland) and a measure of historical temperature change between a baseline period (1901-1930) and the year prior to the end month of biodiversity sampling (see Figure S21 for the duration of each sampling period), standardized by monthly temperature variability in the baseline period [@harris2020; @outhwaite2022]. We standardised temperature changes in this way to capture where temperatures have exceeded the baseline seasonal and interannual variation, a consideration that has previously been identified as important for insects in general [@outhwaite2022]. Given that the PREDICTS database contains a set of biodiversity measurements collected from across studies, we include a set of random intercepts to account for study-level variation, as well as an adjustment for sampling effort. Our set of likely insect pollinators were compiled through an automatic literature scrape, combined with a manual search and verification by a group of pollination ecology experts [@Millard2021]. We then apply these models to predict which locations and crops are likely to be exposed to the greatest losses of pollinator abundance, and thus to face the greatest risk of crop pollination shortfalls. We moderate estimates of risk according to estimates of where crops are grown [@Monfreda2008], how dependent these crops are on animal pollination [@Klein2007], projections of historical and future climate change, and a set of assumptions for the relationship between local pollinator abundance and crop pollination (from linear to highly concave to convex). We focus on future climate projections under two Representative Concentration Pathways (RCP) scenarios: RCP 2.6, which has a multi-model-median predicted 1.5$^\circ$C increase in global average temperatures by 2100 compared to the pre-industrial climate; and RCP 6.0, which has a multi-model-median predicted 3$^\circ$C increase in global average temperatures [@Rogelj2012]. Finally, we combine projected pollination risk with estimates of the trade in pollination-dependent crop production [@silva2021], to predict regions of the world that may be vulnerable to the indirect consequences of crop pollination risk via trade connections.

# Results and Discussion

The abundance of insect pollinators responded strongly to the interaction of recent climate change and land use (Figure 1). Within cropland experiencing novel temperatures (Standardized Temperature Anomaly = 1), pollinator abundance is 61.1% lower than in natural habitat that has not experienced temperature increases. The causal mechanism underpinning this interaction is unclear, but the moderation of microclimatic conditions [@oliver2014] and the absence of a buffering effect of forest within cropland [@deFrenne2019], are likely partly responsible. Our results are qualitatively consistent with recent results for a sample of all insects [@outhwaite2022], but importantly we show that responses to the interactive effects of climate change and land use are stronger for pollinating than non-pollinating insects (Figure 1). This is important as it would indicate that risk inferred from all insect groups will be lower than from insect pollinating taxa alone. We also show that the strength of the interactive effect varies among taxonomic groups, with the strongest effects seen in dipteran and hymenopteran pollinators (Figure S1). Whether the sensitivity of pollinating insects to the interaction of climate change and land use relates directly to their reliance on floral resources, or to other correlated traits typical of pollinators, is unclear, and a combination of both factors is likely to operate. For example, selection of animal pollinated plants is thought to be highly sensitive to climatic conditions such as precipitation and temperature [@rech2016], suggesting that plant-pollinator interactions are highly sensitive to thermal changes. Pollinator pilosity (i.e. hairiness), on the other hand, likely affects an insect’s ability to adapt to changes in climate [@peters2016], and given its nature as a trait typical of bees and hoverflies, tends to be correlated with a reliance on floral resources [@stavert2016]. 

The modelled effects of land-use-climate interactions on pollinator abundance are robust to using threshold temperatures to restrict the months considered to those in which insects are likely to be active (Figure S3), to jack-knifing the predictions for the top 10 sampling methods (Figure S22, see Figure S23 for the full set of sampling methods), and to including an interaction between mean annual temperature and predominant land-use (Table S6; also see Figure S24 showing the correlation between standardised temperature anomaly and mean annual temperature, and Figure S25, suggesting that mean annual temperature may have an effect on primary vegetation but not in cropland). Although the lepidopterans are the only group represented for a standardised temperature anomaly greater than 2 (Figure S1), our results are robust to dropping individual taxonomic families from the model dataset (Figure S2).

![Response of pollinating (A) and non-pollinating (B) insect total abundance to the interactive effect of standardised temperature anomaly and land use (primary vegetation versus cropland) (A: F = 22.4068, p < 0.001; B: F = 10.7520, p < 0.01). Note that abundance is plotted on a log~e~ scale (although the labels are back-transformed). Results are based on linear mixed-effects models. Site numbers are as follows (also see Table S1 and Figure S14 for site spatial distribution): insects known to pollinate (primary vegetation = 1166, cropland = 1507); insects not known to pollinate (primary vegetation = 1747, cropland = 922). See Table S2 for the number of species represented in both the pollinating and non-pollinating groups, Table S3 for AIC and $R^{2}$ values for each model, Figures S18 and S19 for the number of insect pollinating species, Figure S20 for the same figure but with the values of total abundance, and Figure S1 for models by taxonomic order. Shading represents 95% confidence intervals around the mean fitted effect. Green = primary vegetation; yellow = cropland.](`r here::here("outputs/Figures/Fig_1.png")`)

![A schematic of models and inputs for our local production risk measure. Top row: The PREDICTS database (‘Biodiversity assemblages’, subset for a set of ‘Likely animal pollinators’) is used to build a space-for-time model of pollinator biodiversity change, fitting total abundance as a function of an interaction between land-use type and a standardised temperature anomaly of climate change (‘Climate data’ from the Climatic Research Unit). Bottom row: Change in insect pollinator abundance relative to a baseline (where standardised temperature anomaly is 0) is converted into a crop production loss via a set of linear functions, and then converted into a pollination dependent risk by multiplying the expected change by the pollination dependent production in each cell (‘Crop production’ and ‘Pollination dependence’). Economic loss is calculated from production at risk multiplied by crop price. Numbers in brackets for each input represent the source from which the data originated (as listed in the bibliography). Image credits: Bottom right photo, Ionutzmovie (CC BY 3.0); top right photo, gailhampshire (CC BY 2.0).](`r here::here("outputs/Figures/Fig_2.png")`)

We predict that total pollination production risk will increase under all climate scenarios (Figure 3, see Figure 2 for a schematic of our crop pollination risk inputs and models). For all scenarios, our projections use change in pollinating insect abundance as a proxy for the relative risk to the production of crops dependent on insects, incorporating information on where crops are grown worldwide [@Monfreda2008] as well as the fractional dependence of crops on animal pollination [@Klein2007]. Our projections are based on the assumption that a projected loss in pollinator abundance will be associated with risk to crop production from loss of pollination services, according to a function that translates abundance loss into production loss. This linked cascade model allows us to account for uncertainty of the biodiversity-production relationship, which although typically described as positive concave, may vary for crop-pollinator interactions [@paul2020]. We made a decision to focus on abundance in the main text given the mechanistic link between pollinator abundance, pollen load, pollen deposition, and crop pollination. To be complete however, in the supplementary information we also present a measure of risk based on species richness alone (Figure S15 and S16). Our estimates of both relative risk as well as absolute production risk should be interpreted as indices of risk, rather than predictions of the actual amount of production likely to be lost, given the very high uncertainty in how pollinator abundance changes will translate into actual production losses [@aizen2022], and that we do not account for the spatial context of individual cropland areas.

Increases in risk are seen for all assumed relationships between abundance loss and production risk, although the magnitude of changes in relative risk and especially absolute production risk varied widely (Figure 3). The predicted rate of increase in average production risk was substantially higher under RCP (Representative Concentration Pathway) 6.0 than RCP 2.6, suggesting that efforts to mitigate climate change will reduce the risk to future crop production, alongside the many other benefits [@urge2014]. Relative production risk varied strongly between years under an assumption of a concave relationship between pollinator abundance and production (Figure 3). This volatility may be explained by the way in which the non-linearity of abundance/production relationships interacts with inter-annual climate variability caused by the El Nino Southern Oscillation [@timmermann2018]. While increasingly concave assumed relationships between insect abundance loss and crop production risk led to steeper increases in relative production risk with future climate change, absolute production risk was markedly lower, owing to a lower baseline in the present day (Figure 3). Our estimates of risk are based on the distribution of crops as grown in 2000 (see Table S4 for the full list of crops), meaning we do not account for changes in the distribution of crops over time, which are likely to occur as a result of the direct impacts of climate change, indirect effects through the loss of pollinator biodiversity, and socio-economic factors such as price changes in the global markets for particular crops. 

Our projections of crop production risk are robust to variation in climate predictions under different individual climate models (Figure S4), and do not change markedly when abundance loss is capped at the maximum model-fitted value (Figure S5), when lower-quality estimates of crop distribution are dropped (Figure S6), when Chao-estimated species richness is used in place of total abundance in the models and projections (Figure S15 and S16), or when projections are based only on bees as a key pollinating taxon (Figure S17).

![Projected change in total production risk under two RCP scenarios (2.6 and 6.0, see Figure S7 for 8.5) and a set of hypothetical relationships between pollinator abundance and crop production (linear and varying degrees of concavity, defined in the right hand panel). Results are shown both for an index of change in relative risk (A and B) and for the total production potentially at risk (in tonnes) (C and D). For each year into the future, the standardised temperature anomaly was projected globally for all cells with production of crops dependent on animal pollination, using a 3-year rolling average of temperature anomaly estimates in each cell, from an ensemble of different climate models. We used data on crop production for the year 2000 (the latest year when such data are available for all crops). For each annual projection of standardised temperature anomaly, insect pollinator abundance on cropland was predicted according to the model shown in Figure 1A, and then expressed as proportional abundance loss compared to cropland that has experienced no warming (i.e. standardised temperature anomaly of 0). In each cell, the total production of each crop [@Monfreda2008] was multiplied by dependence on animal pollination [@Klein2007], and then adjusted for the predicted percentage reduction in insect pollinator abundance in that cell. These estimates of crop production at risk were summed across crops, and then across all terrestrial cells globally. Lines show different assumed relationships between insect pollinator abundance and crop production: dashed = concave relationships (of differing degrees, indicated by different colours: yellow = most concave; purple/blue = least concave); and solid = linear relationship. See Figure S7 for a set of convex relationships.](`r here::here("outputs/Figures/Fig_3.png")`)

Projected risk to crop production in 2050 from insect pollinator abundance losses, as a proportion of all production in a given location, is highest in the tropical regions of sub-Saharan Africa, South America, and south-east Asia (Figure 4A; see Figure S8 for individual maps of pollination-dependent crop production and the standardized temperature anomaly). In terms of total production potentially at risk, China, India, Indonesia, Brazil, and the Philippines emerge as being most at risk (Figure 4B). Among crops, cocoa is estimated to be at highest risk, by a large margin, especially in Africa, followed by mango (particularly in India) and watermelon (notably in China) (Figure 4B). The risk to cocoa production is particularly significant in light of the social and economic context, as most cocoa is produced on small farms (two to four hectares) that provide income to between 40 and 50 million people globally [@beg2017]. Coffee is also expected to have a combination of relatively high production risk (Figure 4B) and high value, suggesting that regions in which it is grown may experience economic difficulties, unless the pollination service can be replaced cost effectively. Similarly to cocoa, coffee production provides income to millions of small-scale farmers and their families in the tropics [@pham2019]. Therefore, the increased production risk due to loss of pollinators could lead to increased income insecurity for some of the most vulnerable people globally. Our projections of local crop production risk are sensitive to the assumed abundance-production relationship (Figure S9), with the exception of South East Asia, which is consistently projected to have high risk, and the temperate realm, which is consistently projected to have low risk (Figure S10).

It is impossible to predict exactly how our estimates of production risk measure will translate into actual crop production losses. There are multiple uncertainties associated with predicting pollinator biodiversity changes and how this impacts crop production, some of which we explore here (e.g. the relationship between pollinator abundance and crop production), but many of which we do not or cannot (e.g. the changing distribution of crops [@kummu2021], the economic viability of hand pollination [@wurz2021], the buffering effects of managed pollinators [@gonzalez2013], the effects of climate change alone [@settele2016], the uncertainty over whether pollinator abundance is more important than other measures of pollinator diversity [@garibaldi2018; @garibaldi2016], the buffering or magnifying effects of landscape composition or agroforestry [@martin2019; @gonzalez2023], and other technological solutions such as the breeding or engineering of pollinator-independent cultivars [@hamblin2018]). As one example, crops in which hand-pollination is already widely practiced, in particular apple, tomato, kiwi, oilpalm, and vanilla [@wurz2021], will likely be more resilient than our models would predict. Regardless, at the global scale, assuming that our modelled relationships between standardised temperature change and pollinator abundance are genuine and hold into the future, and that the distribution of pollination dependent production does not significantly change, the relative risk we project is likely to be reflected in challenges for crop production. For cocoa, recent research has focused on the direct effects of climate change on crop production [@schroth2016; @ofori2014], often overlooking those that might be pollinator-mediated, probably because the direct effects of climate change are easier to capture, and because the set of cocoa pollinating taxa other than midges is unknown [@claus2018]. Importantly, solutions to direct and pollinator-mediated effects of climate change may differ. For example, shade trees might protect crops from the detrimental effects of extreme temperatures [@schroth2016], but might not for the ceratopogonid fly pollinators on which cocoa pollination depends [@vansynghel2022]. The focus in previous research on direct climate impacts rather than pollinator-mediated effects is a key gap (but see [@giannini2017]), given that some cocoa varieties are limited more by pollination availability then resource availability [@groeneveld2010].

![Projected change globally in crop production estimated to be at risk in 2050 under the RCP 6.0 climate scenario, assuming a linear relationship between insect pollinator abundance loss and production loss for crops dependent on animal pollination. All projections are based on mean projections of the standardized temperature anomaly based on temperature estimates from an ensemble of individual climate models. (A) The sum of crop production at risk across all crops with some dependence on animal pollination, as a proportion of the production of all crops grown in a location ('proportional production risk'). (B) The total crop production at risk for the 7 crops with the highest total pollination dependent production value globally (see Figure S11 for the top 20 crops by pollination dependent production alone, Figure S12 for country level proportional production risk, and Figure S13 for crop level proportional production risk), in million US$ per annum, broken down into four main geographic regions. Each coloured bar represents a pollination dependent crop group: Grey, cocoa; black, tropical fruits (not recorded elsewhere); red, fruits (not recorded elsewhere); orange, mango; dark blue, coffee; yellow, watermelon; green, coconut; and other crops, light blue. Per tonne values of each crop are for the years 2015-2019 (US$ in 2015-2019  values) taken from [@FAO2022], and total pollination dependent production according to [@Monfreda2008] and [@Klein2007]. Each country is indicated according to its ISO3 code.](`r here::here("outputs/Figures/Fig_4.png")`){width=75%}

Countries besides those with high production risk will feel the impact of losses of pollinators and the crops that depend on them, through disruption to imports, especially as the most vulnerable crops tend to be valuable export products such as coffee and cocoa. In absolute terms, large countries  such as China and the United States have the highest total import risks (Figure 5B). The Netherlands emerges as having surprisingly high risk given its size, the third largest overall import risk (Figure 5B), consistent with its status as the greatest importer and second greatest processor of cocoa beans worldwide [@simoes2011; @statista2023]. Import risk per capita (Figure 5A) highlights the challenges that could be faced by nations with limited agricultural production capacity, such as many island countries (e.g. Cayman Islands, Aruba, Singapore, the second, third and fourth highest import risk per capita, respectively) or countries with unfavourable environmental conditions for agriculture (e.g., Mongolia, with the 19th highest import risk per capita). Total import risk per capita tends to be high also in northern and high-income countries, particularly continental western Europe, which has large processing industries for crops such as coffee and cocoa. High income and unfavourable environment for agriculture could both account for high import risk per capita for some countries in the Middle East (United Arab Emirates, Kuwait, Saudi Arabia, which have the 5th, 13th, and 27th highest estimated pollination import risk per capita). Our predictions of import risk are based on trade patterns in the present day [@silva2021], meaning we do not account for changes in trade flows that will likely occur in the future. Our approach also assumes that all crop production produced in a given country is exported. In other words we used our trade pattern data to determine how production at risk within a given country should be split among its importers, but did not have a value for the proportion of production staying in that country.

![Projected total import risk for 2050 under the RCP 6.0 scenario, assuming a linear relationship between insect pollinator abundance loss and production loss. Projections are based on projected changes in the mean standardized temperature anomaly from an ensemble of individual climate models. Import risk is a measure of how the effects of localised production risk might be distributed among other countries, calculated using trade flow data from [@silva2021]. For each yearly time step into the future, local production risk in each spatial cell is attributed to importers according to the quantity of pollination trade imported from each country. For example, if an importer is dependent on 3 countries for imports, at a proportion of 30%, 50%, and 20%, then any change in import risk should scale as a function of the local production risk aggregated at those same proportions. (A) The geographic distribution of total import risk adjusted for country population size and then converted to a percentile. Colours represent each percentile grouping: yellow, 0-25th percentile; orange, 25-50th; purple, 50-75th; dark blue, 75-100th. Inset plot represents the absolute import risk values on a log10 scale (although note that the labels are back-transformed), with the same percentile breakpoints. (B) The total import crop production at risk in thousand tonnes per annum, for the 10 countries with the highest import production at risk. Each country is indicated according to its ISO3 code. 'Other' is the sum of import risk for all other countries in that geographic region. ](`r here::here("outputs/Figures/Fig_5.png")`){width=75%}

Interacting effects of climate change and anthropogenic land use are rapidly restructuring biodiversity [@outhwaite2022; @ganuza2022]. Here we show that the combination of agricultural land use and recent climate change is associated with particularly large reductions in the abundance of insect pollinators. As a result, we predict that the tropics will likely experience the greatest risk of future crop pollination shortfalls, putting at risk the production of crops that depend on insect pollination. Future crop pollination risk is estimated to be highest in areas used to produce cocoa, mango, watermelon, and coffee. Given the many factors that determine crop production and crop price [@gaetano2018], the likely effects of insect pollinator losses on crop production are unclear, and even if they do occur, conclusive attribution is likely to be challenging. Such complications likely in part explain why identifying a strong effect of pollinator losses on global crop yield and price has thus far been so difficult [@Aizen2008; @aizen2009; @garibaldi2011]. Regardless, there is sufficient evidence to suggest that declining insect pollinator abundance will influence crop production risk, particularly for those in the global south [@dicks2021]. Such risk could manifest in the form of direct and immediate losses to crop production through pollinator shortfall, fluctuations over time in the stability of production [@lemanski2022], or through decreased resilience to changes that will happen in conjunction (e.g. the effects of extreme temperature and drought on crop growth). Given the likely buffering effects of landscape composition [@martin2019; @outhwaite2022], greater surrounding natural habitat may help to mitigate these risks. The health, well-being, and livelihoods of a high proportion of the global population, from small farmers to consumers, relies to some extent upon the availability and affordability of crops dependent on animal pollination, which is likely to be put at greater risk as a result of future pollinator losses as land-use and climate changes intensify.

# References
<div id="refs"></div>

# Acknowledgements
Thanks to Richard Gregory, Robin Freeman, and colleagues on the GLITRS project for useful discussions and comments. Thanks to Andy Purvis and Melinda Mills, who both provided support and guidance. Thanks also to Opeyemi Adedoja, Sabrina Gavini, Esther Kioko, Michael Kuhlmann, Zong-Xin Ren, and Manu Saunders, who provided input on our set of likely pollinating species, and to all contributors of the PREDICTS database.

# Funding
JM received PhD funding from the London NERC DTP and the RSPB. JM, TN and CLO receive funding from the UK Natural Environment Research Council (NERC; grant references: NE/R010811/1, NE/V006533/1 and NE/V006800/1). TN and SC receive funding from the UK Economic and Social Research Council (reference: ES/S008160/1). TN is additionally supported by a University Research Fellowship from the Royal Society. LGC was funded by the brazilian Conselho Nacional de Desenvolvimento Científico e Tecnológico [CNPq 307625/2021-4].

# Author Contributions
JM and TN conceived the study. JM, CO, FDSS, JO, LD, LGC, SC, and TN designed the methodology of crop pollination risk and import production risk. All authors edited and approved the final version of the manuscript.

# Competing Interests
All authors declare that they have no competing interests.

# Data and Materials Availability
All code needed to evaluate the conclusions in the paper are present on Zenodo (https://zenodo.org/badge/latestdoi/256482859) and on GitHub (https://github.com/Joemillard/key_tropical_crops_at_risk_from_pollinator_loss).

# Code Availability
Links to all data are currently hosted openly on GitHub here (https://github.com/Joemillard/Worldwide-vulnerability-of-local-pollinator-abundance-and-crop-pollination-to-land-use-and-climate). On publication all primary data and links will be versioned on Zenodo.

# Materials & Correspondence
Correspondence should be addressed to Joseph Millard (joseph.millard@nhm.ac.uk)
